on:
  release:
    branches: main
    types: [created, published, edited]

name: Archive a tagged version

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Get tags and/or branches
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Screenshot Repo
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://github.com/davidwilby/ResearchSoftwareMethods
          destination: assets/images/talk_repo_screenshot.png
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          mkdir build
          quarto render presentation.qmd --output-dir build
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          target-folder: ${{ env.TAG }}
          clean: false
